In [40]:
import tensorflow as tf
from tensorflow import keras
import os
tf.__version__

'1.12.0'

In [41]:
#Example Dataset
(train_images,train_labels),(test_images,test_labels)=tf.keras.datasets.mnist.load_data()
train_labels=train_labels[:1000]
test_labels=test_labels[:1000]


In [42]:
train_images=train_images[:1000].reshape(-1,28*28)/255.0
test_images=test_images[:1000].reshape(-1,28*28)/255.0
print(train_images)
print(test_images)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [43]:
#Define Model
def create_model():
    model=tf.keras.Sequential([
        keras.layers.Dense(512,activation=tf.nn.relu,input_shape=(784,)),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(10,activation=tf.nn.softmax)
    ])
    model.compile(optimizer=tf.train.AdamOptimizer(),
                  loss=tf.keras.losses.sparse_categorical_crossentropy,
                  metrics=['accuracy'])
    return model

model=create_model()
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_24 (Dense)             (None, 512)               401920    
_________________________________________________________________
dropout_12 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_25 (Dense)             (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [44]:
#Save CheckPoints During training
checkpoint_path='/home/shruti/TensorflowSaveAndRestoreModel'
checkpoint_dir= os.path.dirname(checkpoint_path)

In [45]:
cp_callback=tf.keras.callbacks.ModelCheckpoint(checkpoint_path,save_weights_only=True,verbose=1)
model=create_model()
model.fit(train_images,train_labels,epochs=10,validation_data=(test_images,test_labels),callbacks=[cp_callback])

Train on 1000 samples, validate on 1000 samples
Epoch 1/10
 544/1000 [===============>..............] - ETA: 0s - loss: 1.5369 - acc: 0.5643 
Epoch 00001: saving model to /home/shruti/TensorflowSaveAndRestoreModel
1000/1000 [==============================] - 1s 694us/step - loss: 1.1801 - acc: 0.6650 - val_loss: 0.7216 - val_acc: 0.7870
Epoch 2/10
 992/1000 [============================>.] - ETA: 0s - loss: 0.4542 - acc: 0.8659
Epoch 00002: saving model to /home/shruti/TensorflowSaveAndRestoreModel
1000/1000 [==============================] - 0s 163us/step - loss: 0.4547 - acc: 0.8660 - val_loss: 0.5337 - val_acc: 0.8250
Epoch 3/10
 992/1000 [============================>.] - ETA: 0s - loss: 0.3000 - acc: 0.9183
Epoch 00003: saving model to /home/shruti/TensorflowSaveAndRestoreModel
1000/1000 [==============================] - 0s 169us/step - loss: 0.2984 - acc: 0.9190 - val_loss: 0.4625 - val_acc: 0.8500
Epoch 4/10
 960/1000 [===========================>..] - ETA: 0s - loss: 0.2080 - 

In [46]:
!ls {checkpoint_dir}

2018-09-20-07-29-20.030-VBoxSVC-3280.log
anaconda
anaconda3
Anaconda3-5.2.0-Linux-x86_64.sh
checkpoint
Desktop
Documents
Downloads
examples.desktop
google-chrome-stable_current_amd64.deb
java_error_in_PYCHARM_3646.log
java_error_in_PYCHARM_4596.log
java_error_in_PYCHARM.hprof
Machine-Learning
ML-Fellowship
Music
nltk_data
octave-workspace
Old Firefox Data
Pictures
Public
PycharmProjects
python.json
README.md
rtl8723de
rtlwifi_new
seaborn-data
snap
_sysconfigdata_nd.py
Templates
TensorflowSaveAndRestoreModel.data-00000-of-00001
TensorflowSaveAndRestoreModel.index
TensorflowSaveAndRestoreModel.ipynb
Videos


In [47]:
model=create_model()

loss,acc=model.evaluate(test_images,test_labels)
print("Restored Model,Accuracy:{:5.2f}%".format(100*acc))


1000/1000 [==============================] - 0s 306us/step
Restored Model,Accuracy: 9.30%


In [48]:
latest = tf.train.latest_checkpoint(checkpoint_dir)
latest

'/home/shruti/TensorflowSaveAndRestoreModel'